radio:
  ce_pin: 12
  spi_channel: 0
  spi_speed: 100000
  channel: 76
  payload_size: 32
  data_rate: 0
  pa_level: 2
  crc_bytes: 2

addresses:
  address_ground_to_air: "GtoA1"
  address_air_to_ground: "AtoG1" 
